[#140] fix/deployment
- push 오류로 인한.. 재 배포 테스트

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -30,6 +30,12 @@ jobs:
         run: |
            ./gradlew build --no-daemon -x test
 
+      - name: Verify JAR file exists
+        run: |
+          if [ ! -f build/libs/BookFlex-0.0.1-SNAPSHOT.jar ]; then
+            echo "JAR file not found!"; exit 1;
+          fi
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
